"""empty message

Revision ID: 1086194c0f63
Revises: 7bb6696253a8
Create Date: 2018-04-20 10:21:19.749772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1086194c0f63'
down_revision = '7bb6696253a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.drop_index('ix_roles_description', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_roles_description', 'roles', ['description'], unique=True)
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
